---
# This playbook deploys the whole application stack for a jenkins.

# - name: Mount EFS disk
#   become: true
#   hosts: localhost
#   roles:
#     - ansible-role-mount-disks

- name: Install Java
  hosts: localhost
  roles:
    - role: ansible-role-java
      when: "ansible_os_family == 'RedHat'"
      java_packages:
        - java-1.8.0-openjdk

- name: Install SSM Agent and AWS CLI
  become: true
  hosts: localhost
  roles:
    - ansible-role-os-tasks

# - name: Install Docker
#   become: true
#   hosts: localhost
#   roles:
#     - ansible-role-docker

- name: Install Ansible
  hosts: localhost
  roles:
    - role: ansible-role-install-ansible

- name: Install Terraform
  hosts: localhost
  roles:
    - role: ansible-role-terraform

- name: Install Jenkins
  hosts: localhost
  become: true
  vars:
    jenkins_hostname: localhost
    java_packages:
      - openjdk-8-jdk
  roles:
    - role: ansible-role-jenkins