---

jenkins:
    systemMessage: "Jenkins configured automatically by Jenkins Configuration as Code"
    
credentials:
  system:
    domainCredentials:
      - credentials:
        - string:
            scope: GLOBAL
            id: "secret-text"
            secret: "Secret text"
            description: "Secret Text"
        - usernamePassword:
            id: "GIT_ACCESS_TOKEN"
            username: "GIT_ACCESS_TOKEN"
            password: "pass from vault"
            description: "My secret GIT credential"
            scope: GLOBAL
        - file:
            scope: GLOBAL
            id: "secret-file"
            fileName: "mysecretfile.txt"
            secretBytes: "${base64:${readFile:${SECRET_FILE_PATH}}}" # secretBytes requires base64 encoded content

jobs:
  - script: >
      folder('Platform')
  - script: >
      folder('Platform/Services')
  - script: >
      folder('Platform/Services/Company')
  - script: >
      pipelineJob('Platform/Services/Company/DEV') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://gitlab.com/company/folder/folder2/project.git')
                  credentials('GIT_ACCESS_TOKEN')
                }
                branch('*/dev')
              }
            }
            scriptPath("Jenkinsfile")
            lightweight()
          }
        }
      }