---

- name: Ensure {{ jenkins_home }} exists
  file:
    path: "{{ jenkins_home }}"
    state: directory

- name: Copy jenkins.yaml file to the place where it can be read by the plugin
  copy:
    src: "{{ role_path }}/files/jenkins.yaml"
    dest: "{{ jenkins_home }}/jenkins.yaml"
    mode: "0755"